//
//
// CC_TelecommandFactory.h
//
//


#ifndef CC_TELECOMMANDFACTORY_H
#define CC_TELECOMMANDFACTORY_H


#include "../GeneralInclude/ForwardDeclarations.h"
#include "../GeneralInclude/BasicTypes.h"
#include "../Base/CC_RootObject.h"   
#include "../Telecommand/DC_DummyPUSTelecommand.h"  
#include "../Telecommand/DC_DummyTelecommand.h"  
//#include "../Telecommand/DC_PUSControlDataReporting.h"  
//#include "../Telecommand/DC_PUSDefineDataReporting.h"  
#include "../Telecommand/DC_PUSDumpMemoryAbsolute.h"  
#include "../Telecommand/DC_PUSDumpMemoryOffset.h"  
#include "../Telecommand/DC_PUSMemoryLoadAbsolute.h"  
#include "../Telecommand/DC_PUSMemoryLoadOffset.h"  
#include "../Telecommand/DC_TestPUSTelecommand.h"  
#include "../Qom/object.h"


/*
 * Dynamic factory for components of type: <code>Telecommand</code>.
 * A <i>dynamic factory</i> is a component that manages a pool of instances of
 * components of a certain type. Clients of the factory can require one of these
 * instances at run-time. After the factory hands over a component instance to its
 * client, the instance is marked as "in use" and cannot be given to any other
 * clients. When the requesting client has finished using the instance, it should release
 * it by marking it as "no longer in use". This will allow the factory to make it
 * available to other clients that request it. The "in use" status of the component
 * instances is controlled through method <code>setInUse</code> declared on
 * the component instances.
 * <p>
 * A dynamic factory is configured in two steps. The first step is performed
 * by the factory constructor when the internal data structures to hold the component
 * instances are created. The second step is performed during application initialization
 * when the component instances are loaded in the factory. Reconfiguration at run time
 * during normal application operation is not allowed.
 * <p>
 * Dynamic factories are implemented as singletons. They can exist in one single instance
 * that can be accessed through the <code>getInstance</code> method.
 * The one single instance of the class is created the first time that method
 * getInstance is called. In order to avoid possible disruptions of
 * real-time behaviour, applications should ensure that this method has been called
 * at least once before the application enters its operational phase.
 * <p>
 * This factory manages the following component instances:<ul>  
 * <li>Number of instances of type <code>DC_DummyPUSTelecommand</code>: 1</li>    
 * <li>Number of instances of type <code>DC_DummyTelecommand</code>: 2</li>    
 * <li>Number of instances of type <code>DC_PUSControlDataReporting</code>: 1</li>    
 * <li>Number of instances of type <code>DC_PUSDefineDataReporting</code>: 1</li>    
 * <li>Number of instances of type <code>DC_PUSDumpMemoryAbsolute</code>: 1</li>    
 * <li>Number of instances of type <code>DC_PUSDumpMemoryOffset</code>: 1</li>    
 * <li>Number of instances of type <code>DC_PUSMemoryLoadAbsolute</code>: 2</li>    
 * <li>Number of instances of type <code>DC_PUSMemoryLoadOffset</code>: 1</li>    
 * <li>Number of instances of type <code>DC_TestPUSTelecommand</code>: 3</li>    
 * </ul>
 * The code for this class was automatically generated by an XSL program processing
 * the XML-based application model.    
 * @ingroup Telecommand
 * @see Telecommand
 * @author Automatically Generated Class
 * @version 1.0
 */
#define TYPE_CC_TELECOMMANDFACTORY "cc_telecommandfactory"

void CC_TelecommandFactory_register(void);


///////////////////////////////////////////////////////////////////////////////
//
//                            class and struct
//
///////////////////////////////////////////////////////////////////////////////

struct CC_TelecommandFactory {
    CC_RootObject parent;

    unsigned int sizeDummyPUSTelecommand;
    DC_DummyPUSTelecommand **poolDummyPUSTelecommand;

    unsigned int sizeDummyTelecommand;
    DC_DummyTelecommand **poolDummyTelecommand;

    unsigned int sizePUSControlDataReporting;
    DC_PUSControlDataReporting **poolPUSControlDataReporting;

    unsigned int sizePUSDefineDataReporting;
    DC_PUSDefineDataReporting **poolPUSDefineDataReporting;

    unsigned int sizePUSDumpMemoryAbsolute;
    DC_PUSDumpMemoryAbsolute **poolPUSDumpMemoryAbsolute;

    unsigned int sizePUSDumpMemoryOffset;
    DC_PUSDumpMemoryOffset **poolPUSDumpMemoryOffset;

    unsigned int sizePUSMemoryLoadAbsolute;
    DC_PUSMemoryLoadAbsolute **poolPUSMemoryLoadAbsolute;

    unsigned int sizePUSMemoryLoadOffset;
    DC_PUSMemoryLoadOffset **poolPUSMemoryLoadOffset;

    unsigned int sizeTestPUSTelecommand;
    DC_TestPUSTelecommand **poolTestPUSTelecommand;
};


struct CC_TelecommandFactoryClass {
    CC_RootObjectClass parent_class;
};


#define CC_TELECOMMANDFACTORY_GET_CLASS(obj) \
        OBJECT_GET_CLASS(CC_TelecommandFactoryClass, obj, TYPE_CC_TELECOMMANDFACTORY)

#define CC_TELECOMMANDFACTORY_CLASS(klass) \
        OBJECT_CLASS_CHECK(CC_TelecommandFactoryClass, klass, TYPE_CC_TELECOMMANDFACTORY)

#define CC_TELECOMMANDFACTORY(obj) \
        OBJECT_CHECK(CC_TelecommandFactory, obj, TYPE_CC_TELECOMMANDFACTORY)


CC_TelecommandFactory* CC_TelecommandFactory_new(void);


///////////////////////////////////////////////////////////////////////////////
//
//                            class method(s) declaration
//
///////////////////////////////////////////////////////////////////////////////

/**
 * Get the single instance of this singleton class. If the instance does not
 * yet exist, it is created.
 */
CC_TelecommandFactory* CC_TelecommandFactory_getInstance(void);



///////////////////////////////////////////////////////////////////////////////
//
//                 non-virtual member method(s) declaration
//
///////////////////////////////////////////////////////////////////////////////

/**
 * General interface for all Telecommand setter methods
 *
 * @param i the index in the internal array
 * @param pItem the component instance
 */
void CC_TelecommandFactory_setTelecommand
(
    CC_TelecommandFactory *This, 
    unsigned int i,
    Telecommand *pItem
);

/**
 * Load one instance of type <code>DC_DummyPUSTelecommand</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_DummyPUSTelecommand</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setDummyPUSTelecommand
(
    CC_TelecommandFactory *This, 
    unsigned int i,
    DC_DummyPUSTelecommand *pItem
);

/**
 * Return the number of component instances of type <code>DC_DummyPUSTelecommand</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberDummyPUSTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_DummyPUSTelecommand</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_DummyPUSTelecommand</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_DummyPUSTelecommand</code>
 */
unsigned int CC_TelecommandFactory_getCapacityDummyPUSTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_DummyPUSTelecommand</code>.
 * This method scans all the entries in the factory of type <code>DC_DummyPUSTelecommand</code>
 * and returns the first one which is not in use. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller.      
 * @return the allocated component instance or null if no free instances were found
 */
DC_DummyPUSTelecommand* CC_TelecommandFactory_allocateDummyPUSTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Check whether a non-allocated component instance of type <code>DC_DummyPUSTelecommand</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_DummyPUSTelecommand     
 * @return true if free instances of type DC_DummyPUSTelecommand are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreeDummyPUSTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Load one instance of type <code>DC_DummyTelecommand</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_DummyTelecommand</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setDummyTelecommand
(
    CC_TelecommandFactory *This,
    unsigned int i,
    DC_DummyTelecommand *pItem
);

/**
 * Return the number of component instances of type <code>DC_DummyTelecommand</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberDummyTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_DummyTelecommand</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_DummyTelecommand</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_DummyTelecommand</code>
 */
unsigned int CC_TelecommandFactory_getCapacityDummyTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_DummyTelecommand</code>.
 * This method scans all the entries in the factory of type <code>DC_DummyTelecommand</code>
 * and returns the first one which is not in use. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller.      
 * @return the allocated component instance or null if no free instances were found
 */
DC_DummyTelecommand* CC_TelecommandFactory_allocateDummyTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Check whether a non-allocated component instance of type <code>DC_DummyTelecommand</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_DummyTelecommand     
 * @return true if free instances of type DC_DummyTelecommand are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreeDummyTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Load one instance of type <code>DC_PUSControlDataReporting</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_PUSControlDataReporting</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setPUSControlDataReporting
(
    CC_TelecommandFactory *This, 
    unsigned int i,
    DC_PUSControlDataReporting *pItem
);

/**
 * Return the number of component instances of type <code>DC_PUSControlDataReporting</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberPUSControlDataReporting
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_PUSControlDataReporting</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_PUSControlDataReporting</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_PUSControlDataReporting</code>
 */
unsigned int CC_TelecommandFactory_getCapacityPUSControlDataReporting
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_PUSControlDataReporting</code>.
 * This method scans all the entries in the factory of type <code>DC_PUSControlDataReporting</code>
 * and returns the first one which is not in use. 
 * In addition to verifyin that the returned component is not in use, this method also performs a check
 * on the value of the component configuration parameters. The folloging configuration parameters 
 * are checked: MaxNumberSID.
 * This method has a parameter matching each component configuration parameter. A component instance is
 * returned only if the value of the component configuration parameter is greater than or equal to the method
 * parameter. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller. 
 * @param MaxNumberSID minimum value for a component configuration parameter      
 * @return the allocated component instance or null if no free instances were found
 */
DC_PUSControlDataReporting* CC_TelecommandFactory_allocatePUSControlDataReporting
(
    CC_TelecommandFactory *This, 
    unsigned int MaxNumberSID
);

/**
 * Check whether a non-allocated component instance of type <code>DC_PUSControlDataReporting</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_PUSControlDataReporting
 * @param MaxNumberSID minimum value for a component configuration parameter      
 * @return true if free instances of type DC_PUSControlDataReporting are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreePUSControlDataReporting
(
    CC_TelecommandFactory *This, 
    unsigned int MaxNumberSID
);

/**
 * Load one instance of type <code>DC_PUSDefineDataReporting</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_PUSDefineDataReporting</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setPUSDefineDataReporting
(
    CC_TelecommandFactory *This, 
    unsigned int i,
    DC_PUSDefineDataReporting *pItem
);

/**
 * Return the number of component instances of type <code>DC_PUSDefineDataReporting</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberPUSDefineDataReporting
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_PUSDefineDataReporting</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_PUSDefineDataReporting</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_PUSDefineDataReporting</code>
 */
unsigned int CC_TelecommandFactory_getCapacityPUSDefineDataReporting
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_PUSDefineDataReporting</code>.
 * This method scans all the entries in the factory of type <code>DC_PUSDefineDataReporting</code>
 * and returns the first one which is not in use. 
 * In addition to verifyin that the returned component is not in use, this method also performs a check
 * on the value of the component configuration parameters. The folloging configuration parameters 
 * are checked: NumberOfRawData.
 * This method has a parameter matching each component configuration parameter. A component instance is
 * returned only if the value of the component configuration parameter is greater than or equal to the method
 * parameter. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller. 
 * @param NumberOfRawData minimum value for a component configuration parameter      
 * @return the allocated component instance or null if no free instances were found
 */
DC_PUSDefineDataReporting* CC_TelecommandFactory_allocatePUSDefineDataReporting
(
    CC_TelecommandFactory *This, 
    unsigned int NumberOfRawData
);

/**
 * Check whether a non-allocated component instance of type <code>DC_PUSDefineDataReporting</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_PUSDefineDataReporting
 * @param NumberOfRawData minimum value for a component configuration parameter      
 * @return true if free instances of type DC_PUSDefineDataReporting are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreePUSDefineDataReporting
(
    CC_TelecommandFactory *This, 
    unsigned int NumberOfRawData
);

/**
 * Load one instance of type <code>DC_PUSDumpMemoryAbsolute</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_PUSDumpMemoryAbsolute</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setPUSDumpMemoryAbsolute
(
    CC_TelecommandFactory *This, 
    unsigned int i,
    DC_PUSDumpMemoryAbsolute *pItem
);

/**
 * Return the number of component instances of type <code>DC_PUSDumpMemoryAbsolute</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberPUSDumpMemoryAbsolute
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_PUSDumpMemoryAbsolute</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_PUSDumpMemoryAbsolute</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_PUSDumpMemoryAbsolute</code>
 */
unsigned int CC_TelecommandFactory_getCapacityPUSDumpMemoryAbsolute
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_PUSDumpMemoryAbsolute</code>.
 * This method scans all the entries in the factory of type <code>DC_PUSDumpMemoryAbsolute</code>
 * and returns the first one which is not in use. 
 * In addition to verifyin that the returned component is not in use, this method also performs a check
 * on the value of the component configuration parameters. The folloging configuration parameters 
 * are checked: NumberOfRawData.
 * This method has a parameter matching each component configuration parameter. A component instance is
 * returned only if the value of the component configuration parameter is greater than or equal to the method
 * parameter. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller. 
 * @param NumberOfRawData minimum value for a component configuration parameter      
 * @return the allocated component instance or null if no free instances were found
 */
DC_PUSDumpMemoryAbsolute* CC_TelecommandFactory_allocatePUSDumpMemoryAbsolute
(
    CC_TelecommandFactory *This, 
    unsigned int NumberOfRawData
);

/**
 * Check whether a non-allocated component instance of type <code>DC_PUSDumpMemoryAbsolute</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_PUSDumpMemoryAbsolute
 * @param NumberOfRawData minimum value for a component configuration parameter      
 * @return true if free instances of type DC_PUSDumpMemoryAbsolute are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreePUSDumpMemoryAbsolute
(
    CC_TelecommandFactory *This, 
    unsigned int NumberOfRawData
);

/**
 * Load one instance of type <code>DC_PUSDumpMemoryOffset</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_PUSDumpMemoryOffset</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setPUSDumpMemoryOffset
(
    CC_TelecommandFactory *This, 
    unsigned int i, 
    DC_PUSDumpMemoryOffset *pItem
);

/**
 * Return the number of component instances of type <code>DC_PUSDumpMemoryOffset</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberPUSDumpMemoryOffset
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_PUSDumpMemoryOffset</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_PUSDumpMemoryOffset</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_PUSDumpMemoryOffset</code>
 */
unsigned int CC_TelecommandFactory_getCapacityPUSDumpMemoryOffset
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_PUSDumpMemoryOffset</code>.
 * This method scans all the entries in the factory of type <code>DC_PUSDumpMemoryOffset</code>
 * and returns the first one which is not in use. 
 * In addition to verifyin that the returned component is not in use, this method also performs a check
 * on the value of the component configuration parameters. The folloging configuration parameters 
 * are checked: NumberOfRawData.
 * This method has a parameter matching each component configuration parameter. A component instance is
 * returned only if the value of the component configuration parameter is greater than or equal to the method
 * parameter. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller. 
 * @param NumberOfRawData minimum value for a component configuration parameter      
 * @return the allocated component instance or null if no free instances were found
 */
DC_PUSDumpMemoryOffset* CC_TelecommandFactory_allocatePUSDumpMemoryOffset
(
    CC_TelecommandFactory *This, 
    unsigned int NumberOfRawData
);

/**
 * Check whether a non-allocated component instance of type <code>DC_PUSDumpMemoryOffset</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_PUSDumpMemoryOffset
 * @param NumberOfRawData minimum value for a component configuration parameter      
 * @return true if free instances of type DC_PUSDumpMemoryOffset are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreePUSDumpMemoryOffset
(
    CC_TelecommandFactory *This, 
    unsigned int NumberOfRawData
);

/**
 * Load one instance of type <code>DC_PUSMemoryLoadAbsolute</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_PUSMemoryLoadAbsolute</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setPUSMemoryLoadAbsolute
(
    CC_TelecommandFactory *This, 
    unsigned int i,
    DC_PUSMemoryLoadAbsolute *pItem
);

/**
 * Return the number of component instances of type <code>DC_PUSMemoryLoadAbsolute</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberPUSMemoryLoadAbsolute
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_PUSMemoryLoadAbsolute</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_PUSMemoryLoadAbsolute</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_PUSMemoryLoadAbsolute</code>
 */
unsigned int CC_TelecommandFactory_getCapacityPUSMemoryLoadAbsolute
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_PUSMemoryLoadAbsolute</code>.
 * This method scans all the entries in the factory of type <code>DC_PUSMemoryLoadAbsolute</code>
 * and returns the first one which is not in use. 
 * In addition to verifyin that the returned component is not in use, this method also performs a check
 * on the value of the component configuration parameters. The folloging configuration parameters 
 * are checked: MaxNumberData, MaxNumberBlocks.
 * This method has a parameter matching each component configuration parameter. A component instance is
 * returned only if the value of the component configuration parameter is greater than or equal to the method
 * parameter. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller. 
 * @param MaxNumberData minimum value for a component configuration parameter 
 * @param MaxNumberBlocks minimum value for a component configuration parameter      
 * @return the allocated component instance or null if no free instances were found
 */
DC_PUSMemoryLoadAbsolute* CC_TelecommandFactory_allocatePUSMemoryLoadAbsolute
(
    CC_TelecommandFactory *This, 
    unsigned int MaxNumberData, 
    unsigned int MaxNumberBlocks
);

/**
 * Check whether a non-allocated component instance of type <code>DC_PUSMemoryLoadAbsolute</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_PUSMemoryLoadAbsolute
 * @param MaxNumberData minimum value for a component configuration parameter 
 * @param MaxNumberBlocks minimum value for a component configuration parameter      
 * @return true if free instances of type DC_PUSMemoryLoadAbsolute are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreePUSMemoryLoadAbsolute
(
    CC_TelecommandFactory *This, 
    unsigned int MaxNumberData,
    unsigned int MaxNumberBlocks
);

/**
 * Load one instance of type <code>DC_PUSMemoryLoadOffset</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_PUSMemoryLoadOffset</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setPUSMemoryLoadOffset
(
    CC_TelecommandFactory *This,
    unsigned int i,
    DC_PUSMemoryLoadOffset *pItem
);

/**
 * Return the number of component instances of type <code>DC_PUSMemoryLoadOffset</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberPUSMemoryLoadOffset
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_PUSMemoryLoadOffset</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_PUSMemoryLoadOffset</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_PUSMemoryLoadOffset</code>
 */
unsigned int CC_TelecommandFactory_getCapacityPUSMemoryLoadOffset
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_PUSMemoryLoadOffset</code>.
 * This method scans all the entries in the factory of type <code>DC_PUSMemoryLoadOffset</code>
 * and returns the first one which is not in use. 
 * In addition to verifyin that the returned component is not in use, this method also performs a check
 * on the value of the component configuration parameters. The folloging configuration parameters 
 * are checked: MaxNumberData, MaxNumberBlocks.
 * This method has a parameter matching each component configuration parameter. A component instance is
 * returned only if the value of the component configuration parameter is greater than or equal to the method
 * parameter. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller. 
 * @param MaxNumberData minimum value for a component configuration parameter 
 * @param MaxNumberBlocks minimum value for a component configuration parameter      
 * @return the allocated component instance or null if no free instances were found
 */
DC_PUSMemoryLoadOffset* CC_TelecommandFactory_allocatePUSMemoryLoadOffset
(
    CC_TelecommandFactory *This, 
    unsigned int MaxNumberData, 
    unsigned int MaxNumberBlocks
);

/**
 * Check whether a non-allocated component instance of type <code>DC_PUSMemoryLoadOffset</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_PUSMemoryLoadOffset
 * @param MaxNumberData minimum value for a component configuration parameter 
 * @param MaxNumberBlocks minimum value for a component configuration parameter      
 * @return true if free instances of type DC_PUSMemoryLoadOffset are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreePUSMemoryLoadOffset
(
    CC_TelecommandFactory *This, 
    unsigned int MaxNumberData, 
    unsigned int MaxNumberBlocks
);

/**
 * Load one instance of type <code>DC_TestPUSTelecommand</code> in the
 * factory. The component instances managed by the factory are internally stored in an
 * array. This method loads the i-th element of the array. The argument i should lie
 * in the interval [0, N-1] where N is the number of component instances of type
 * <code>DC_TestPUSTelecommand</code>. The value of N is defined by
 * the class constructor.
 * <p>
 * The "in use" status of a newly loaded component is initialized
 * to: "component is not in use".
 * <p>
 * This is an initialization method that should only be called during the application
 * configuration phase.
 * @param i the index in the internal array
 * @param pItem the component instance
 */
static void setTestPUSTelecommand
(
    CC_TelecommandFactory *This, 
    unsigned int i,
    DC_TestPUSTelecommand *pItem
);

/**
 * Return the number of component instances of type <code>DC_TestPUSTelecommand</code>
 * that are currently allocated. A component instance is allocated if its "in use" status is
 * equal to: "component is in use".
 * @return the number of allocated component instances
 */
unsigned int CC_TelecommandFactory_getNumberTestPUSTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Return the number of component instances of type <code>DC_TestPUSTelecommand</code>
 * that are in the factory. The value returned is the maximum number of component instances of
 * type <code>DC_TestPUSTelecommand</code> that can be allocated.
 * @return the total number of component instances in the factory of
 * type <code>DC_TestPUSTelecommand</code>
 */
unsigned int CC_TelecommandFactory_getCapacityTestPUSTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Allocate one instance of type <code>DC_TestPUSTelecommand</code>.
 * This method scans all the entries in the factory of type <code>DC_TestPUSTelecommand</code>
 * and returns the first one which is not in use. 
 * Before being returned to the caller, 
 * the status of the component instance is changed to: "in use". A client that receives
 * a component instance through a call to this method, should release the instance when it
 * no longer needs it. This can be done by calling
 * method <code>CC_TelecommandFactory_setInUse(false)</code> on the component itself.
 * <p>
 * If no free component instances are found, then the method returns null. Note that no
 * event report is generated to record the failure to allocate a component instance. Event
 * reporting is the responsibility of the caller.      
 * @return the allocated component instance or null if no free instances were found
 */
DC_TestPUSTelecommand* CC_TelecommandFactory_allocateTestPUSTelecommand
(
    CC_TelecommandFactory *This
);

/**
 * Check whether a non-allocated component instance of type <code>DC_TestPUSTelecommand</code>
 * is available within the factory. If this method return true, then the corresponding
 * <code>allocate</code> method is guaranteed to return a non-null value.
 * The method parameters are used as in the corresponding <code>allocate</code> method.
 * @see #allocateDC_TestPUSTelecommand     
 * @return true if free instances of type DC_TestPUSTelecommand are available, 
 * false otherwise
 */
bool CC_TelecommandFactory_isFreeTestPUSTelecommand
(
    CC_TelecommandFactory *This
);


#endif
